import React, { StrictMode } from "react";
import { AppProps } from "next/app";
import Head from "next/head";

import "@/styles/globals.css";
import heart from "./../assets/img/blue-heart.png";
import Image from "next/image";
import Layout from "./../components/layout/layout/layout.component";
import Header from "../components/templates/header.component";

const App: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StrictMode>
        <main>
          <Layout
            isSidebarOpen={true}
            header={
              <Header
                title="Online Store"
                icon={
                  <Image
                    src={heart}
                    alt={"brand-icon"}
                    height={55}
                    width={70}
                  />
                }
              />
            }
            content={<Component {...pageProps} />}
          />
        </main>
      </StrictMode>
    </>
  );
};

export default App;
